Feature/ask before deleting not empty list
TomBursch/kitchenowl pull request #575
Opened 2024-12-12 12:15 UTC by RedX2501

Will ask if it is ok to delete the list if it still has items.

The function as factored out so I can later use it in the shopping lists overview when deleting shopping lists from there.
Please let me know if that is fine or you'd like to have a component.

This PR is still a draft due to it's dependency on other PRs. I'd like to get your feedback early so I know if the style is good.

2024-12-12 12:16 UTC, RedX2501 commented
[] do not merge as it depends on other PRs.

2024-12-12 17:40 UTC, TomBursch commented
Looks good already, thanks for this. If you have the time can you split the documentation into it's own PR? Thanks!

2024-12-13 11:54 UTC, TomBursch requested changes
Only one minor thing, otherwise it LGTM

2024-12-13 11:54 UTC, TomBursch commented on kitchenowl/lib/l10n/app_en.arb
> +  "shoppingListContainsEntries": "{entriesCount, plural, =0{The shopping list contains no entrie(s).} =1{The shopping list contains 1 entry.} other{The shopping list contains {entriesCount} entries.}
Can we order these alphabetically? Just move this up two lines. Same for the `@shoppingListContainsEntries`.

2024-12-13 12:19 UTC, RedX2501 commented on kitchenowl/lib/l10n/app_en.arb
> +  "shoppingListContainsEntries": "{entriesCount, plural, =0{The shopping list contains no entrie(s).} =1{The shopping list contains 1 entry.} other{The shopping list contains {entriesCount} entries.}
Done

2024-12-13 12:41 UTC, TomBursch approved these changes

2024-12-13 12:43 UTC, merged